version: '3.8'
services:
  web:
    build: site
    container_name: apache-git
    ports :
      - "81:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: mysql-git
    ports :
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mvcdocker2
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-git
    depends_on:
      - database
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1